# Generated by Django 4.2.16 on 2024-11-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('data_source_url', models.URLField()),
                ('tariff', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_nl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_be', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('free_shipping_nl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('free_shipping_be', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_note', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('include', models.BooleanField(default=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('new', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_r', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, default='', max_length=1000)),
                ('image', models.URLField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.affiliate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.affiliatecategory')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_games', to='games.game')),
            ],
        ),
    ]
