# Generated by Django 4.2.16 on 2024-11-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='affiliategame',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.affiliatecategory'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ean',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='affiliategame',
            unique_together={('affiliate', 'game')},
        ),
        migrations.RemoveField(
            model_name='affiliategame',
            name='ean',
        ),
    ]
