# Generated by Django 4.2.16 on 2024-11-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_id_alter_affiliategame_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='stock',
        ),
    ]
