# Generated by Django 4.2.16 on 2024-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_affiliate_data_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='program',
            field=models.CharField(choices=[('Adtraction', 'Adtraction'), ('TradeTracker', 'TradeTracker'), ('Awin', 'Awin'), ('Daisycon', 'Daisycon')], max_length=100),
        ),
    ]
