# Generated by Django 4.2.16 on 2024-11-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_affiliate_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_lowest_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
